// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZOe3oCvKZI8jIMSeQco-oKA-jOold77U',
    appId: '1:245153874573:web:a2800e66b9d59bfe1558c4',
    messagingSenderId: '245153874573',
    projectId: 'cookie-b6108',
    authDomain: 'cookie-b6108.firebaseapp.com',
    storageBucket: 'cookie-b6108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq56l5WGLPejREYoafcwxbrBq7G7SLr-I',
    appId: '1:245153874573:android:4572791dad5e5a1a1558c4',
    messagingSenderId: '245153874573',
    projectId: 'cookie-b6108',
    storageBucket: 'cookie-b6108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8eJG6UhK5rKMd_IacsBNlQA3cGlX_iEM',
    appId: '1:245153874573:ios:4ae8d2125c084e6b1558c4',
    messagingSenderId: '245153874573',
    projectId: 'cookie-b6108',
    storageBucket: 'cookie-b6108.appspot.com',
    iosBundleId: 'com.ys.testPr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8eJG6UhK5rKMd_IacsBNlQA3cGlX_iEM',
    appId: '1:245153874573:ios:264136f62434499a1558c4',
    messagingSenderId: '245153874573',
    projectId: 'cookie-b6108',
    storageBucket: 'cookie-b6108.appspot.com',
    iosBundleId: 'com.example.testPr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZOe3oCvKZI8jIMSeQco-oKA-jOold77U',
    appId: '1:245153874573:web:61c6ecbe71e9a5fe1558c4',
    messagingSenderId: '245153874573',
    projectId: 'cookie-b6108',
    authDomain: 'cookie-b6108.firebaseapp.com',
    storageBucket: 'cookie-b6108.appspot.com',
  );
}
